### ISSUE TITLE
Rename Midas to Open Opportunities

### ISSUE THREAD

**Issue by dhcole** [18F/openopps-platform#907]
Midas is this open source project, and Open Opportunities is a government website run through GSA that uses Midas.  This distinction sometimes causes confusion, and Midas is not a helpful name for understanding the purpose of this software.  By renaming Midas to Open Opportunities, we can simply refer to one thing most of the time  "Open Opportunities" which has open source software behind it. 

This really is an administrative change and wouldn't have any material impact on users of the software, especially those implementing custom themes, like CrowdWorks at State.

- [x] community test server
- [x] footer: "Powered by Midas" should be "Powered by Open Opportunities"
- [x] logo: https://github.com/18F/midas/issues/1080
- [x] Readme text
- [x] screenshots: in /docs/screenshots
- [x] github repository
- [x] waffle: https://waffle.io/18F/openopps-platform
- [x] 3rd-party services URLs pointing to the new github repository for services that don't support redirects ( i.e. waffle )
- [x] https://pages.18f.gov/midas/
- [x] see if we can redirect pages.18f.gov: https://github.com/18F/pages-server/issues/13
- [x] wiki 
- [x] markdown documentation
- [x] 18F project tracking 
- [x] 18F dashboard
- [x] slack channels
- [x] video chat rooms
- [More line-items below](https://github.com/18F/openopps-platform/issues/907#issuecomment-165487884)

Open Opportunities program is run by OCSIT as a service for federal employees at any federal agency.
logo: 

OpenOpps platform is open source software.  Originally developed by the State Dept. under the code-name “Midas,” moved to 18F in 2014.
logo

contact: openopps@gsa.gov 
live site: openopps.digitalgov.gov
open source dev server: openopps-test.18f.gov
staging server:  openopps-staging.18f.gov

github:
github.com/18f/openopps-platform
github.com/18f/open-opportunities-theme

**Comment by jeremiak** [comment]
I support the renaming. It is unnecessarily confusing to try and explain the difference between the platform and the major implementation. It seems to make more sense to me to have OpenOpps be the "default" installation and ensure that State's implementation is more of a theme (though I'm making a lot of assumptions here about how CrowdWork works so please correct me if this is ridiculous).

**Comment by mokk083** [comment]
Renaming sounds easier than it is. When you rebrand something, you should hope to realign it to the brand's core values, along with an upgrade of visual identity. Open Opportunities is too clunky, I would try more iterations with your core team to find something with 1. less syllables, 2. colloquial language 3. friendly. If you guys need someone to create a brand guide with your renaming, I can help.

Secondly, my university is looking to use MIDAS to encourage entrepreneurship at the school and encourage cross disciplinary collaboration. (Maybe that gives you ideas for your rebrand? =P "Collab Jobs", "Co-Kreate", etc) Do you guys have a product roadmap by any chance? We plan on developing more features ourselves, and we want to know what you guys have planned.

**Comment by dhcole** [comment]
Hi @mokk083, thanks for weighing in. It's great to hear that you're considering using Midas. Let us know how we can help. We're finalizing a short-term roadmap that will take us through the end of the year. I'll ping back here when it's posted.

On the naming front, Open Opportunities already exists and is an established program at GSA. We call the implementation of Midas "Open Opportunities". The main point I'm raising here is consolidating on one name for both the software and its implementation. It sounds like that's a valuable approach.

As for renaming the existing program, that would be a much bigger task, but I appreciate your thoughts on this. We'll discuss internally to see whether we can have the larger conversation on naming.

**Comment by dhcole** [comment]
The roadmap is here now: https://github.com/18F/midas/wiki/Roadmap

We're moving ahead with renaming the application to match the program, so let's transition this issue to a list of things that need to be changed over.

**Comment by dhcole** [comment]
- [ ] github repository
- [ ] community test server
- [ ] wiki / readme / markdown documentation
- [ ] 18F project tracking, website, and dashboard

**Comment by jeremiak** [comment]
- [ ] slack channels

**Comment by dhcole** [comment]
> footer: "Powered by Midas" should be "Powered by Open Opportunities"

How about "Powered by open source" since it links to GitHub.

**Comment by ultrasaurus** [comment]
draft text for README and ideas for screenshots here:  https://docs.google.com/a/gsa.gov/document/d/13JsT_0iecI_bKufI6R8fc0TM5GOXzHGE2AgRHkep9Q0/pub

**Comment by NoahKunin** [comment]
Slack Channel task partially done. Slack enforces a 21 character limit, so flipping our public channel to the new name goes beyond it with the `-public` suffix, so we'll need a slightly different formulation from the team on that one.

**Comment by rogeruiz** [comment]
Hey, @NoahKunin. I spoke to @dhcole and he mentioned that the name change from `midas-public` to `openopps-public` should be fine given the hard 21-character limit in Slack.

**Comment by dhcole** [comment]
:+1:

**Comment by NoahKunin** [comment]
Done

On Thu, Nov 19, 2015 at 8:21 AM, Dave Cole <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openopps-platform/issues/907#issuecomment-158106915>
> .
>



-- 
Noah Kunin
18F Infrastructure Director | @18F <https://twitter.com/18F>

**Comment by rogeruiz** [comment]
The wiki is updated! Please [take a look here](https://github.com/18F/openopps-platform/wiki). Looks like after the `dev-about` branch is reviewed and merged we'll have this issue closed :dancer:

**Comment by ultrasaurus** [comment]
Any reason not to delete "Modal Component Usage" from front page?  currently strike thru

**Comment by rogeruiz** [comment]
hmm I'm not sure what content used to exist on that page, but I've now removed it from the wiki's homepage for now. Thanks @ultrasaurus

**Comment by rogeruiz** [comment]
Still seeing some remnants of `midas` in the codebase. I'll be keeping track of all the places here:

- [ ] Application config still defaults to `midas`
- [ ] CSS payload references `midas`
